from lists import extList 

dynamicOfficeDict = {
    'ERMKT': [
        extList['ERMKT']['city'],
        extList['ERMKT']['company'],
        extList['ERMKT']['country'],
        extList['ERMKT']['description'],
        extList['ERMKT']['office'],
        extList['ERMKT']['zipcode'],
        extList['ERMKT']['script'],
        extList['ERMKT']['server'],
        extList['ERMKT']['state'],
        extList['ERMKT']['address'],
        "ERM Research"
    ],
    'LIVE-CHI': [
        extList['LIVE-CHI']['city'],
        extList['LIVE-CHI']['company'],
        extList['LIVE-CHI']['country'],
        extList['LIVE-CHI']['description'],
        extList['LIVE-CHI']['office'],
        extList['LIVE-CHI']['zipcode'],
        extList['LIVE-CHI']['script'],
        extList['LIVE-CHI']['server'],
        extList['LIVE-CHI']['state'],
        extList['LIVE-CHI']['address'],
        "Allied Live"
    ],
    'LIVE-WDC': [
        extList['LIVE-WDC']['city'],
        extList['LIVE-WDC']['company'],
        extList['LIVE-WDC']['country'],
        extList['LIVE-WDC']['description'],
        extList['LIVE-WDC']['office'],
        extList['LIVE-WDC']['zipcode'],
        extList['LIVE-WDC']['script'],
        extList['LIVE-WDC']['server'],
        extList['LIVE-WDC']['state'],
        extList['LIVE-WDC']['address'],
        "Allied Live"
    ],
    'LIVE-LA': [
        extList['LIVE-LA']['city'],
        extList['LIVE-LA']['company'],
        extList['LIVE-LA']['country'],
        extList['LIVE-LA']['description'],
        extList['LIVE-LA']['office'],
        extList['LIVE-LA']['zipcode'],
        extList['LIVE-LA']['script'],
        extList['LIVE-LA']['server'],
        extList['LIVE-LA']['state'],
        extList['LIVE-LA']['address'],
        "Allied Live"
    ],
    'BOSTON': [
        extList['BOSTON']['city'],
        extList['BOSTON']['company'],
        extList['BOSTON']['country'],
        extList['BOSTON']['description'],
        extList['BOSTON']['office'],
        extList['BOSTON']['zipcode'],
        extList['BOSTON']['script'],
        extList['BOSTON']['server'],
        extList['BOSTON']['state'],
        extList['BOSTON']['address'],
        "Allied Integrated Marketing"
    ],
    'NEWYORK': [
        extList['NEWYORK']['city'],
        extList['NEWYORK']['company'],
        extList['NEWYORK']['country'],
        extList['NEWYORK']['description'],
        extList['NEWYORK']['office'],
        extList['NEWYORK']['zipcode'],
        extList['NEWYORK']['script'],
        extList['NEWYORK']['server'],
        extList['NEWYORK']['state'],
        extList['NEWYORK']['address'],
        "Allied Integrated Marketing"
    ],
    'LOSANGELES': [
        extList['LOSANGELES']['city'],
        extList['LOSANGELES']['company'],
        extList['LOSANGELES']['country'],
        extList['LOSANGELES']['description'],
        extList['LOSANGELES']['office'],
        extList['LOSANGELES']['zipcode'],
        extList['LOSANGELES']['script'],
        extList['LOSANGELES']['server'],
        extList['LOSANGELES']['state'],
        extList['LOSANGELES']['address'],
        "Allied Integrated Marketing"
    ],
    'ATLANTA': [
        extList['ATLANTA']['city'],
        extList['ATLANTA']['company'],
        extList['ATLANTA']['country'],
        extList['ATLANTA']['description'],
        extList['ATLANTA']['office'],
        extList['ATLANTA']['zipcode'],
        extList['ATLANTA']['script'],
        extList['ATLANTA']['server'],
        extList['ATLANTA']['state'],
        extList['ATLANTA']['address'],
        "Allied Integrated Marketing"
    ],
    'ATLANTA-VININGS': [
        extList['ATLANTA-VININGS']['city'],
        extList['ATLANTA-VININGS']['company'],
        extList['ATLANTA-VININGS']['country'],
        extList['ATLANTA-VININGS']['description'],
        extList['ATLANTA-VININGS']['office'],
        extList['ATLANTA-VININGS']['zipcode'],
        extList['ATLANTA-VININGS']['script'],
        extList['ATLANTA-VININGS']['server'],
        extList['ATLANTA-VININGS']['state'],
        extList['ATLANTA-VININGS']['address'],
        "Allied Integrated Marketing"
    ],
    'CHICAGO': [
        extList['CHICAGO']['city'],
        extList['CHICAGO']['company'],
        extList['CHICAGO']['country'],
        extList['CHICAGO']['description'],
        extList['CHICAGO']['office'],
        extList['CHICAGO']['zipcode'],
        extList['CHICAGO']['script'],
        extList['CHICAGO']['server'],
        extList['CHICAGO']['state'],
        extList['CHICAGO']['address'],
        "Allied Integrated Marketing"
    ],
    'CLEVELAND': [
        extList['CLEVELAND']['city'],
        extList['CLEVELAND']['company'],
        extList['CLEVELAND']['country'],
        extList['CLEVELAND']['description'],
        extList['CLEVELAND']['office'],
        extList['CLEVELAND']['zipcode'],
        extList['CLEVELAND']['script'],
        extList['CLEVELAND']['server'],
        extList['CLEVELAND']['state'],
        extList['CLEVELAND']['address'],
        "Allied Integrated Marketing"
    ],
    'DALLAS': [
        extList['DALLAS']['city'],
        extList['DALLAS']['company'],
        extList['DALLAS']['country'],
        extList['DALLAS']['description'],
        extList['DALLAS']['office'],
        extList['DALLAS']['zipcode'],
        extList['DALLAS']['script'],
        extList['DALLAS']['server'],
        extList['DALLAS']['state'],
        extList['DALLAS']['address'],
        "Allied Integrated Marketing"
    ],
    'DENVER': [
        extList['DENVER']['city'],
        extList['DENVER']['company'],
        extList['DENVER']['country'],
        extList['DENVER']['description'],
        extList['DENVER']['office'],
        extList['DENVER']['zipcode'],
        extList['DENVER']['script'],
        extList['DENVER']['server'],
        extList['DENVER']['state'],
        extList['DENVER']['address'],
        "Allied Integrated Marketing"
    ],
    'DETROIT': [
        extList['DETROIT']['city'],
        extList['DETROIT']['company'],
        extList['DETROIT']['country'],
        extList['DETROIT']['description'],
        extList['DETROIT']['office'],
        extList['DETROIT']['zipcode'],
        extList['DETROIT']['script'],
        extList['DETROIT']['server'],
        extList['DETROIT']['state'],
        extList['DETROIT']['address'],
        "Allied Integrated Marketing"
    ],
    'FLORIDA': [
        extList['FLORIDA']['city'],
        extList['FLORIDA']['company'],
        extList['FLORIDA']['country'],
        extList['FLORIDA']['description'],
        extList['FLORIDA']['office'],
        extList['FLORIDA']['zipcode'],
        extList['FLORIDA']['script'],
        extList['FLORIDA']['server'],
        extList['FLORIDA']['state'],
        extList['FLORIDA']['address'],
        "Allied Integrated Marketing"
    ],
    'HOUSTON': [
        extList['HOUSTON']['city'],
        extList['HOUSTON']['company'],
        extList['HOUSTON']['country'],
        extList['HOUSTON']['description'],
        extList['HOUSTON']['office'],
        extList['HOUSTON']['zipcode'],
        extList['HOUSTON']['script'],
        extList['HOUSTON']['server'],
        extList['HOUSTON']['state'],
        extList['HOUSTON']['address'],
        "Allied Integrated Marketing"
    ],
    'KANSASCITY': [
        extList['KANSASCITY']['city'],
        extList['KANSASCITY']['company'],
        extList['KANSASCITY']['country'],
        extList['KANSASCITY']['description'],
        extList['KANSASCITY']['office'],
        extList['KANSASCITY']['zipcode'],
        extList['KANSASCITY']['script'],
        extList['KANSASCITY']['server'],
        extList['KANSASCITY']['state'],
        extList['KANSASCITY']['address'],
        "Allied Integrated Marketing"
    ],
    'LASVEGAS': [
        extList['LASVEGAS']['city'],
        extList['LASVEGAS']['company'],
        extList['LASVEGAS']['country'],
        extList['LASVEGAS']['description'],
        extList['LASVEGAS']['office'],
        extList['LASVEGAS']['zipcode'],
        extList['LASVEGAS']['script'],
        extList['LASVEGAS']['server'],
        extList['LASVEGAS']['state'],
        extList['LASVEGAS']['address'],
        "Allied Integrated Marketing"
    ],
    'MINNEAPOLIS': [
        extList['MINNEAPOLIS']['city'],
        extList['MINNEAPOLIS']['company'],
        extList['MINNEAPOLIS']['country'],
        extList['MINNEAPOLIS']['description'],
        extList['MINNEAPOLIS']['office'],
        extList['MINNEAPOLIS']['zipcode'],
        extList['MINNEAPOLIS']['script'],
        extList['MINNEAPOLIS']['server'],
        extList['MINNEAPOLIS']['state'],
        extList['MINNEAPOLIS']['address'],
        "Allied Integrated Marketing"
    ],
    'PHILADELPHIA': [
        extList['PHILADELPHIA']['city'],
        extList['PHILADELPHIA']['company'],
        extList['PHILADELPHIA']['country'],
        extList['PHILADELPHIA']['description'],
        extList['PHILADELPHIA']['office'],
        extList['PHILADELPHIA']['zipcode'],
        extList['PHILADELPHIA']['script'],
        extList['PHILADELPHIA']['server'],
        extList['PHILADELPHIA']['state'],
        extList['PHILADELPHIA']['address'],
        "Allied Integrated Marketing"
    ],
    'PHOENIX': [
        extList['PHOENIX']['city'],
        extList['PHOENIX']['company'],
        extList['PHOENIX']['country'],
        extList['PHOENIX']['description'],
        extList['PHOENIX']['office'],
        extList['PHOENIX']['zipcode'],
        extList['PHOENIX']['script'],
        extList['PHOENIX']['server'],
        extList['PHOENIX']['state'],
        extList['PHOENIX']['address'],
        "Allied Integrated Marketing"
    ],
    'SANFRANCISCO': [
        extList['SANFRANCISCO']['city'],
        extList['SANFRANCISCO']['company'],
        extList['SANFRANCISCO']['country'],
        extList['SANFRANCISCO']['description'],
        extList['SANFRANCISCO']['office'],
        extList['SANFRANCISCO']['zipcode'],
        extList['SANFRANCISCO']['script'],
        extList['SANFRANCISCO']['server'],
        extList['SANFRANCISCO']['state'],
        extList['SANFRANCISCO']['address'],
        "Allied Integrated Marketing"
    ],
    'SANDIEGO': [
        extList['SANDIEGO']['city'],
        extList['SANDIEGO']['company'],
        extList['SANDIEGO']['country'],
        extList['SANDIEGO']['description'],
        extList['SANDIEGO']['office'],
        extList['SANDIEGO']['zipcode'],
        extList['SANDIEGO']['script'],
        extList['SANDIEGO']['server'],
        extList['SANDIEGO']['state'],
        extList['SANDIEGO']['address'],
        "Allied Integrated Marketing"
    ],
    'SEATTLE': [
        extList['SEATTLE']['city'],
        extList['SEATTLE']['company'],
        extList['SEATTLE']['country'],
        extList['SEATTLE']['description'],
        extList['SEATTLE']['office'],
        extList['SEATTLE']['zipcode'],
        extList['SEATTLE']['script'],
        extList['SEATTLE']['server'],
        extList['SEATTLE']['state'],
        extList['SEATTLE']['address'],
        "Allied Integrated Marketing"
    ],
    'STLOUIS': [
        extList['STLOUIS']['city'],
        extList['STLOUIS']['company'],
        extList['STLOUIS']['country'],
        extList['STLOUIS']['description'],
        extList['STLOUIS']['office'],
        extList['STLOUIS']['zipcode'],
        extList['STLOUIS']['script'],
        extList['STLOUIS']['server'],
        extList['STLOUIS']['state'],
        extList['STLOUIS']['address'],
        "Allied Integrated Marketing"
    ],
    'WASHINGTONDC': [
        extList['WASHINGTONDC']['city'],
        extList['WASHINGTONDC']['company'],
        extList['WASHINGTONDC']['country'],
        extList['WASHINGTONDC']['description'],
        extList['WASHINGTONDC']['office'],
        extList['WASHINGTONDC']['zipcode'],
        extList['WASHINGTONDC']['script'],
        extList['WASHINGTONDC']['server'],
        extList['WASHINGTONDC']['state'],
        extList['WASHINGTONDC']['address'],
        "Allied Integrated Marketing"
    ],
    'TORONTO': [
        extList['TORONTO']['city'],
        extList['TORONTO']['company'],
        extList['TORONTO']['country'],
        extList['TORONTO']['description'],
        extList['TORONTO']['office'],
        extList['TORONTO']['zipcode'],
        extList['TORONTO']['script'],
        extList['TORONTO']['server'],
        extList['TORONTO']['state'],
        extList['TORONTO']['address'],
        "Allied Integrated Marketing"
    ],
    'GCM-LA': [
        extList['GCM-LA']['city'],
        extList['GCM-LA']['company'],
        extList['GCM-LA']['country'],
        extList['GCM-LA']['description'],
        extList['GCM-LA']['office'],
        extList['GCM-LA']['zipcode'],
        extList['GCM-LA']['script'],
        extList['GCM-LA']['server'],
        extList['GCM-LA']['state'],
        extList['GCM-LA']['address'],
        "Allied Experiential"
   ],
    'GCM-NY': [
        extList['GCM-NY']['city'],
        extList['GCM-NY']['company'],
        extList['GCM-NY']['country'],
        extList['GCM-NY']['description'],
        extList['GCM-NY']['office'],
        extList['GCM-NY']['zipcode'],
        extList['GCM-NY']['script'],
        extList['GCM-NY']['server'],
        extList['GCM-NY']['state'],
        extList['GCM-NY']['address'],
        "Allied Experiential"
   ]
}
