extList = {
    'ERMKT': {
        'city':'New York',
        'company':'ERM Research',
        'country':'US',
        'description':'ERM',
        'office':'ERM',
        'zipcode':'10001',
        'script':'login.bat',
        'server':'ermkt.alliedadvpub.com',
        'state':'New York',
        'address':'5 Penn Plaza',
        },
    'LIVE-CHI': {
        'city':'Chicago',
        'company':'Allied Live',
        'country':'US',
        'description':'AL-Chicago',
        'office':'Chicago',
        'zipcode':'60611',
        'script':'liveCHIlogin.bat',
        'server':'live.alliedadvpub.com',
        'state':'Illinois',
        'address':'500 North Michigan Ave, Suite 700',
        },
    'LIVE-WDC': {
        'city':'Washington DC',
        'company':'Allied Live',
        'country':'US',
        'description':'AL-WDC',
        'office':'DC',
        'zipcode':'20036',
        'script':'livelogin.bat',
        'server':'live.alliedadvpub.com',
        'state':'DC',
        'address':'1726 M Street, N.W. Suite 400',
        },
    'LIVE-LA': {
        'city':'Los Angeles',
        'company':'Allied Live',
        'country':'US',
        'description':'AL-LA',
        'office':'Los Angeles',
        'zipcode':'90028',
        'script':'liveLAlogin.bat',
        'server':'live.alliedadvpub.com',
        'state':'California',
        'address':'6908 Hollywood Blvd.',
        },
    'BOSTON': {
        'city':'Boston',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Boston',
        'office':'Boston',
        'zipcode':'02142',
        'script':'smslsbos.bat',
        'server':'alliedadvpub.com',
        'state':'Massachusetts',
        'address':'55 Cambridge Parkway, Suite 200',
        },
    'NEWYORK': {
        'city':'New York',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'New York',
        'office':'New York',
        'zipcode':'10001',
        'script':'smslsny.bat',
        'server':'alliedadvpub.com',
        'state':'New York',
        'address':'5 Penn Plaza, Floor 21',
        },
    'LOSANGELES': {
        'city':'Los Angeles',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Los Angeles',
        'office':'Los Angeles',
        'zipcode':'90028',
        'script':'smslsla.bat',
        'server':'losangeles.alliedadvpub.com',
        'state':'California',
        'address':'6908 Hollywood Blvd.',
        },
    'ATLANTA': {
        'city':'Atlanta',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Atlanta',
        'office':'Atlanta',
        'zipcode':'30305',
        'script':'smslsatl.bat',
        'server':'atl.alliedadvpub.com',
        'state':'Georgia',
        'address':'3565 Piedmont Road, Building 2 Suite 700',
        },
    'ATLANTA-VININGS': {
        'city':'Atlanta',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Atlanta-MI',
        'office':'Atlanta-MI',
        'zipcode':'30339',
        'script':'smslsatl-mi.bat',
        'server':'alliedadvpub.com',
        'state':'Georgia',
        'address':'2727 Paces Ferry Road, SE Bldg. 2, Suite 450',
        },
    'CHICAGO': {
        'city':'Chicago',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Chicago',
        'office':'Chicago',
        'zipcode':'60611',
        'script':'smslschi.bat',
        'server':'chi.alliedadvpub.com',
        'state':'Illinois',
        'address':'500 North Michigan Ave. Suite 700',
        },
    'CLEVELAND': {
        'city':'Cleveland',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Cleveland',
        'office':'Cleveland',
        'zipcode':'44118`',
        'script':'smslscle.bat',
        'server':'cle.alliedadvpub.com',
        'state':'Ohio',
        'address':'1846 Coventry Road, Suite 300',
        },
    'DALLAS': {
        'city':'Dallas',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Dallas',
        'office':'Dallas',
        'zipcode':'75038',
        'script':'smslsdal.bat',
        'server':'alliedadvpub.com',
        'state':'Texas',
        'address':'4500 Fuller Drive, Suite #160',
        },
    'DENVER': {
        'city':'Denver',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Denver',
        'office':'Denver',
        'zipcode':'80203',
        'script':'smslsden.bat',
        'server':'den.alliedadvpub.com',
        'state':'Colorado',
        'address':'600 Grant Street, Suite 725',
        },
    'DETROIT': {
        'city':'Detroit',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Detroit',
        'office':'Detroit',
        'zipcode':'48304',
        'script':'smslsdet.bat',
        'server':'det.alliedadvpub.com',
        'state':'Michigan',
        'address':'40900 N. Woodward Ave, Suite 305',
        },
    'FLORIDA': {
        'city':'Fort Lauderdale',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Florida',
        'office':'Florida',
        'zipcode':'48304',
        'script':'smslsfll.bat',
        'server':'florida.alliedadvpub.com',
        'state':'Florida',
        'address':'6400 N. Andrews Avenue, Suite 470',
        },
    'HOUSTON': {
        'city':'Houston',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Houston',
        'office':'Houston',
        'zipcode':'77027',
        'script':'smslshou.bat',
        'server':'alliedadvpub.com',
        'state':'Texas',
        'address':'1455 West Loop South, Suite 210',
        },
    'KANSASCITY': {
        'city':'Kansas City',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Kansas City',
        'office':'Kansas City',
        'zipcode':'64108',
        'script':'smslskci.bat',
        'server':'kci.alliedadvpub.com',
        'state':'Missouri',
        'address':'1656 Washington Street, Suite 150',
        },
    'LASVEGAS': {
        'city':'Las Vegas',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Las Vegas',
        'office':'Las Vegas',
        'zipcode':'89102',
        'script':'smslslas.bat',
        'server':'alliedadvpub.com',
        'state':'Nevada',
        'address':'241 W. Charleston Blvd., Suite 150',
        },
    'MINNEAPOLIS': {
        'city':'Minneapolis',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Minneapolis',
        'office':'Minneapolis',
        'zipcode':'55403',
        'script':'smslsmsp.bat',
        'server':'msp.alliedadvpub.com',
        'state':'Minnesota',
        'address':'1128 Harmon Place, Suite #302',
        },
    'PHILADELPHIA': {
        'city':'Philadelphia',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Philadelphia',
        'office':'Philadelphia',
        'zipcode':'19103',
        'script':'smslsphl.bat',
        'server':'phl.alliedadvpub.com',
        'state':'Pennsylvania',
        'address':'2005 Market Street, Suite 300',
        },
    'PHOENIX': {
        'city':'Phoenix',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Phoenix',
        'office':'Phoenix',
        'zipcode':'85254',
        'script':'smslsphx.bat',
        'server':'phx.alliedadvpub.com',
        'state':'Arizona',
        'address':'11333 N. Scottsdale Road, Suite 150',
        },
    'SANFRANCISCO': {
        'city':'San Francisco',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'San Francisco',
        'office':'San Francisco',
        'zipcode':'94104',
        'script':'smslssfo.bat',
        'server':'sfo.alliedadvpub.com',
        'state':'California',
        'address':'180 Sansome St. #200',
        },
    'SANDIEGO': {
        'city':'San Diego',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'San Diego',
        'office':'San Diego',
        'zipcode':'92110',
        'script':'smslssan.bat',
        'server':'san.alliedadvpub.com',
        'state':'California',
        'address':'3990 Old Town Avenue, Suite B-206',
        },
    'SEATTLE': {
        'city':'Seattle',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Seattle',
        'office':'Seattle',
        'zipcode':'98119',
        'script':'smslssea.bat',
        'server':'sea.alliedadvpub.com',
        'state':'Washington',
        'address':'100 West Harrison, South Tower, Suite 430',
        },
    'STLOUIS': {
        'city':'St. Louis',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'St. Louis',
        'office':'St. Louis',
        'zipcode':'63119',
        'script':'smslsstl.bat',
        'server':'stlouis.alliedadvpub.com',
        'state':'Missouri',
        'address':'103 W. Lockwood, Suite 204',
        },
    'WASHINGTONDC': {
        'city':'Washington DC',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Washington DC',
        'office':'Washington DC',
        'zipcode':'20036',
        'script':'smsls.wdc',
        'server':'wdc.alliedadvpub.com',
        'state':'District of Columbia',
        'address':'1726 M Street, N.W. Suite 400',
        },
    'TORONTO': {
        'city':'Toronto',
        'company':'Allied Integrated Marketing',
        'country':'CA',
        'description':'Toronto',
        'office':'Toronto',
        'zipcode':'M4T 1L9',
        'script':'smslstor.bat',
        'server':'alliedadvpub.com',
        'state':'Toronto',
        'address':'21 St. Clair Avenue East, Suite 701',
        },
    'GCM-LA': {
        'city':'Los Angeles',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'GCM-Los Angeles',
        'office':'GCM-Los Angeles',
        'zipcode':'90028',
        'script':'smslsgcmla.bat',
        'server':'losangeles.alliedadvpub.com',
        'state':'California',
        'address':'6908 Hollywood Blvd, FL 3',
        },
    'GCM-NY': {
        'city':'New York',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'GCM-New York',
        'office':'GCM-New York',
        'zipcode':'10003',
        'script':'smslsgcmny.bat',
        'server':'alliedadvpub.com',
        'state':'New York',
        'address':'111 E. 12th St., 2nd Floor',
        }
}
