extList = {
    'ERMKT': {
        'city':'New York',
        'company':'ERM Research',
        'country':'US',
        'description':'ERM',
        'office':'ERM',
        'zipcode':'10001',
        'script':'login.bat',
        'server':'ermkt.alliedadvpub.com',
        'state':'New York',
        'address':'5 Penn Plaza',
        },
    'LIVE-CHI': {
        'city':'Chicago',
        'company':'Allied Live',
        'country':'US',
        'description':'AL-Chicago',
        'office':'Chicago',
        'zipcode':'FILL IN',
        'script':'FILL IN',
        'server':'live.alliedadvpub.com',
        'state':'Illinois',
        'address':'FILL IN',
        },
    'LIVE-WDC': {
        'city':'Washington DC',
        'company':'Allied Live',
        'country':'US',
        'description':'AL-WDC',
        'office':'DC',
        'zipcode':'FILL IN',
        'script':'FILL IN',
        'server':'live.alliedadvpub.com',
        'state':'District of Columbia',
        'address':'FILL IN',
        },
    'LIVE-LA': {
        'city':'Los Angeles',
        'company':'Allied Live',
        'country':'US',
        'description':'AL-LA',
        'office':'Los Angeles',
        'zipcode':'FILL IN',
        'script':'FILL IN',
        'server':'live.alliedadvpub.com',
        'state':'California',
        'address':'FILL IN',
        },
    'BOSTON': {
        'city':'Boston',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Boston',
        'office':'Boston',
        'zipcode':'FILL IN',
        'script':'FILL IN',
        'server':'alliedadvpub.com',
        'state':'Massachusetts',
        'address':'FILL IN',
        },
    'NEWYORK': {
        'city':'New York',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'New York',
        'office':'New York',
        'zipcode':'10001',
        'script':'smslsny.bat',
        'server':'alliedadvpub.com',
        'state':'New York',
        'address':'5 Penn Plaza, Floor 21',
        },
    'LOSANGELES': {
        'city':'Los Angeles',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Los Angeles',
        'office':'Los Angeles',
        'zipcode':'FILL IN',
        'script':'FILL IN',
        'server':'losangeles.alliedadvpub.com',
        'state':'California',
        'address':'FILL IN',
        },
    'ATLANTA': {
        'city':'Atlanta',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Atlanta',
        'office':'Atlanta',
        'zipcode':'FILL IN',
        'script':'smslsatl.bat',
        'server':'atl.alliedadvpub.com',
        'state':'Georgia',
        'address':'FILL IN',
        },
    'ATLANTA-VININGS': {
        'city':'Atlanta',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Atlanta-MI',
        'office':'Atlanta-MI',
        'zipcode':'FILL IN',
        'script':'smslsatl-mi.bat',
        'server':'alliedadvpub.com',
        'state':'Georgia',
        'address':'FILL IN',
        },
    'CHICAGO': {
        'city':'Chicago',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Chicago',
        'office':'Chicago',
        'zipcode':'FILL IN',
        'script':'smslschi.bat',
        'server':'chi.alliedadvpub.com',
        'state':'Illinois',
        'address':'FILL IN',
        },
    'CLEVELAND': {
        'city':'Cleveland',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Cleveland',
        'office':'Cleveland',
        'zipcode':'FILL IN`',
        'script':'smslscle.bat',
        'server':'cle.alliedadvpub.com',
        'state':'Ohio',
        'address':'FILL IN',
        },
    'DALLAS': {
        'city':'Dallas',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Dallas',
        'office':'Dallas',
        'zipcode':'FILL IN',
        'script':'smslsdal.bat',
        'server':'alliedadvpub.com',
        'state':'Texas',
        'address':'FILL IN',
        },
    'DENVER': {
        'city':'Denver',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Denver',
        'office':'Denver',
        'zipcode':'FILL IN',
        'script':'smslsden.bat',
        'server':'den.alliedadvpub.com',
        'state':'Colorado',
        'address':'FILL IN',
        },
    'DETROIT': {
        'city':'Detroit',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Detroit',
        'office':'Detroit',
        'zipcode':'FILL IN',
        'script':'smslsdet.bat',
        'server':'det.alliedadvpub.com',
        'state':'Michigan',
        'address':'FILL IN',
        },
    'FLORIDA': {
        'city':'Fort Lauderdale',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Florida',
        'office':'Florida',
        'zipcode':'FILL IN',
        'script':'smslsfll.bat',
        'server':'florida.alliedadvpub.com',
        'state':'Florida',
        'address':'FILL IN',
        },
    'HOUSTON': {
        'city':'Houston',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Houston',
        'office':'Houston',
        'zipcode':'FILL IN',
        'script':'smslshou.bat',
        'server':'alliedadvpub.com',
        'state':'Texas',
        'address':'FILL IN',
        },
    'KANSASCITY': {
        'city':'Kansas City',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Kansas City',
        'office':'Kansas City',
        'zipcode':'FILL IN',
        'script':'smslskci.bat',
        'server':'kci.alliedadvpub.com',
        'state':'Missouri',
        'address':'FILL IN',
        },
    'LASVEGAS': {
        'city':'Las Vegas',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Las Vegas',
        'office':'Las Vegas',
        'zipcode':'FILL IN',
        'script':'smslslas.bat',
        'server':'alliedadvpub.com',
        'state':'Nevada',
        'address':'FILL IN',
        },
    'MINNEAPOLIS': {
        'city':'Minneapolis',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Minneapolis',
        'office':'Minneapolis',
        'zipcode':'FILL IN',
        'script':'smslsmsp.bat',
        'server':'msp.alliedadvpub.com',
        'state':'Minnesota',
        'address':'FILL IN',
        },
    'PHILADELPHIA': {
        'city':'Philadelphia',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Philadelphia',
        'office':'Philadelphia',
        'zipcode':'FILL IN',
        'script':'smslsphl.bat',
        'server':'phl.alliedadvpub.com',
        'state':'Pennsylvania',
        'address':'FILL IN',
        },
    'PHOENIX': {
        'city':'Phoenix',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Phoenix',
        'office':'Phoenix',
        'zipcode':'FILL IN',
        'script':'smslsphx.bat',
        'server':'phx.alliedadvpub.com',
        'state':'Arizona',
        'address':'FILL IN',
        },
    'SANFRANCISCO': {
        'city':'San Francisco',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'San Francisco',
        'office':'San Francisco',
        'zipcode':'FILL IN',
        'script':'smslssfo.bat',
        'server':'sfo.alliedadvpub.com',
        'state':'California',
        'address':'FILL IN',
        },
    'SANDIEGO': {
        'city':'San Diego',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'San Diego',
        'office':'San Diego',
        'zipcode':'FILL IN',
        'script':'smslssan.bat',
        'server':'san.alliedadvpub.com',
        'state':'California',
        'address':'FILL IN',
        },
    'SEATTLE': {
        'city':'Seattle',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Seattle',
        'office':'Seattle',
        'zipcode':'FILL IN',
        'script':'smslssea.bat',
        'server':'sea.alliedadvpub.com',
        'state':'Washington',
        'address':'FILL IN',
        },
    'STLOUIS': {
        'city':'St. Louis',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'St. Louis',
        'office':'St. Louis',
        'zipcode':'FILL IN',
        'script':'smslsstl.bat',
        'server':'stlouis.alliedadvpub.com',
        'state':'Missouri',
        'address':'FILL IN',
        },
    'WASHINGTONDC': {
        'city':'Washington DC',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'Washington DC',
        'office':'Washington DC',
        'zipcode':'FILL IN',
        'script':'smsls.wdc',
        'server':'wdc.alliedadvpub.com',
        'state':'District of Columbia',
        'address':'FILL IN',
        },
    'TORONTO': {
        'city':'Toronto',
        'company':'Allied Integrated Marketing',
        'country':'CA',
        'description':'Toronto',
        'office':'Toronto',
        'zipcode':'FILL IN',
        'script':'smslstor.bat',
        'server':'alliedadvpub.com',
        'state':'Toronto',
        'address':'FILL IN',
        },
    'GCM-LA': {
        'city':'Los Angeles',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'GCM-Los Angeles',
        'office':'GCM-Los Angeles',
        'zipcode':'FILL IN',
        'script':'FILL IN',
        'server':'losangeles.alliedadvpub.com',
        'state':'California',
        'address':'FILL IN',
        },
    'GCM-NY': {
        'city':'New York',
        'company':'Allied Integrated Marketing',
        'country':'US',
        'description':'GCM-New York',
        'office':'GCM-New York',
        'zipcode':'FILL IN',
        'script':'FILL IN',
        'server':'alliedadvpub.com',
        'state':'New York',
        'address':'FILL IN',
        }
}
